### PR TITLE
V8 API patches

### PR DESCRIPTION
**Pull request by tarelda**
I patched all the differences between api v7 and v8. As far as I tested it works.

### CODE REVIEW

**Comment by ubuntudroid** [comment]
Thanks a lot, @tarelda ! 🙏 Unfortunately I'm not maintaining this anymore, nor am I using Gnome Shell, but I'll still merge this for the benefit of everyone.

**Comment by tarelda** [comment]
I did it since I use it daily and imho it is only useful extension for todoist. 
If I have enough time I will try to make few enhancements like:
- drop down with list of tasks,
- provisions to make task complete,
- localization.
Also I know that I made myself to patch it after more than 6 months it stopped working properly ;)

**Comment by ubuntudroid** [comment]
Sounds great! ❤️  

As this repo isn't properly maintained anymore by myself, I guess it would be best to fork it instead and work on the fork. That way you don't need to wait for me to merge your features into master. 😴

**Comment by tarelda** [comment]
I added two promised features:

- adjustable refresh interval,
- dropdown list of due tasks.

It is all available in my fork now :)

**Comment by tarelda** [comment]
@ubuntudroid I separated my fork into another repository to make it github searchable (https://github.com/tarelda/todoist-indicator). Hope you don't mind. Feel free to link it if you want to direct people towards it as atm it is the only one that supports V8 API.

**Comment by ubuntudroid** [comment]
@tarelda done, I've linked your project in the README. Well done! :)

**Pull request merged**
